# Generated by Django 3.1.6 on 2021-09-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='main',
            new_name='sender',
        ),
    ]
