# Generated by Django 3.1.6 on 2021-02-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0007_auto_20210209_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7516939660', editable=False, max_length=10, unique=True),
        ),
    ]
