# Generated by Django 3.1.6 on 2021-02-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0008_auto_20210210_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7595526000', editable=False, max_length=10, unique=True),
        ),
    ]
