# Generated by Django 3.1.6 on 2021-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0009_auto_20210210_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7504156000', editable=False, max_length=10, unique=True),
        ),
    ]
