# Generated by Django 3.1.6 on 2021-02-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0012_auto_20210210_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_History',
            new_name='TransactionHistory',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7511014665', editable=False, max_length=10, unique=True),
        ),
    ]
