# Generated by Django 3.1.6 on 2021-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0015_auto_20210210_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7520578582', editable=False, max_length=10, unique=True),
        ),
    ]
