# Generated by Django 3.1.6 on 2021-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0017_auto_20210213_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7596820327', editable=False, max_length=10, unique=True),
        ),
    ]
