# Generated by Django 3.1.6 on 2021-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0018_auto_20210213_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(blank=True, default='7584150769', editable=False, max_length=10, unique=True),
        ),
    ]
