# Generated by Django 3.1.6 on 2021-03-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets', '0021_auto_20210322_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
